import ConstsType from '../types/ConstsType';
import { CreditCardReward, CreditCardRewards } from '../types/CreditCardType';

const AuthErrorMessages = {
  invalidEmail: 'Invalid Email',
  invalidPassword: 'Invalid Password',
  passwordsDoNotMatch: 'Passwords Do Not Match',
  userAlreadyExists: 'User Already Exists',
  userNotFound: 'User Not Found\nEither Email or Password is Incorrect',
  errorCreatingUser: 'Error Creating User',
  tooManyAttepts:
    'Too Many Attempts\nCheck Your Email for Further Instructions',
  invalidCode:
    'The code is not correct\nEither your email is not correct or you entered an invalid code',
  errorChangingPassword: 'Error Changing Password',
  sentRestEmail: 'Check Your Email for Further Instructions',
  invalidToken: 'Invalid Token\nPlease Contact Support',
};

const dummyProfile = {
  //Need to change this with an api call
  id: 1,
  name: 'John Doe',
  email: 'johndoe@gmail.com',
  username: 'johndoe',
  phone: '1234567890',
  address: '1234 Main St',
  city: 'Anytown',
  state: 'CA',
  zip: '12345',
  subscribed: true,
  //password: 'JohnDoe1234!',
};

const dummyCreditCards = [
  {
    id: 1,
    cardNumber: '1234 5678 9012 3456',
    name: 'John Doe',
    expirationDate: '12/24',
    securityCode: '123',
    cardType: 'Visa',
  },
  {
    id: 2,
    cardNumber: '2345 6789 0123 4567',
    name: 'Jane Smith',
    expirationDate: '11/25',
    securityCode: '456',
    cardType: 'MasterCard',
  },
  {
    id: 3,
    cardNumber: '3456 7890 1234 5678',
    name: 'Mike Johnson',
    expirationDate: '10/26',
    securityCode: '789',
    cardType: 'Discover',
  },
  {
    id: 4,
    cardNumber: '4567 8901 2345 6789',
    name: 'Sara Williams',
    expirationDate: '09/27',
    securityCode: '234',
    cardType: 'American Express',
  },
  {
    id: 5,
    cardNumber: '5678 9012 3456 7890',
    name: 'David Lee',
    expirationDate: '08/28',
    securityCode: '567',
    cardType: 'Visa',
  },
  {
    id: 6,
    cardNumber: '6789 0123 4567 8901',
    name: 'Amy Brown',
    expirationDate: '07/29',
    securityCode: '890',
    cardType: 'MasterCard',
  },
  {
    id: 7,
    cardNumber: '7890 1234 5678 9012',
    name: 'Chris Davis',
    expirationDate: '06/30',
    securityCode: '345',
    cardType: 'Discover',
  },
  {
    id: 8,
    cardNumber: '8901 2345 6789 0123',
    name: 'Emily White',
    expirationDate: '05/31',
    securityCode: '678',
    cardType: 'American Express',
  },
  {
    id: 9,
    cardNumber: '9012 3456 7890 1234',
    name: 'Kevin Johnson',
    expirationDate: '04/32',
    securityCode: '901',
    cardType: 'Visa',
  },
  {
    id: 10,
    cardNumber: '4321 8765 0987 6543',
    name: 'Laura Black',
    expirationDate: '03/33',
    securityCode: '432',
    cardType: 'MasterCard',
  },
];

const dummyCreditCardRewards: CreditCardReward[] = [
  {
    id: 0,
    creditCardId: 1,
    name: 'Reward 1',
    description: 'Description for Reward 1',
    amount: 0.02,
    date: '2023-10-24',
  },
  {
    id: 1,
    creditCardId: 2,
    name: 'Reward 2',
    description: 'Description for Reward 2',
    amount: 0.03,
    date: '2023-10-25',
  },
  {
    id: 2,
    creditCardId: 3,
    name: 'Reward 3',
    description: 'Description for Reward 3',
    amount: 0.01,
    date: '2023-10-26',
  },
  {
    id: 3,
    creditCardId: 4,
    name: 'Reward 4',
    description: 'Description for Reward 4',
    amount: 0.04,
    date: '2023-10-27',
  },
  {
    id: 4,
    creditCardId: 5,
    name: 'Reward 5',
    description: 'Description for Reward 5',
    amount: 0.02,
    date: '2023-10-28',
  },
  {
    id: 5,
    creditCardId: 6,
    name: 'Reward 6',
    description: 'Description for Reward 6',
    amount: 0.03,
    date: '2023-10-29',
  },
  {
    id: 6,
    creditCardId: 7,
    name: 'Reward 7',
    description: 'Description for Reward 7',
    amount: 0.02,
    date: '2023-10-30',
  },
  {
    id: 7,
    creditCardId: 8,
    name: 'Reward 8',
    description: 'Description for Reward 8',
    amount: 0.01,
    date: '2023-10-31',
  },
  {
    id: 8,
    creditCardId: 9,
    name: 'Reward 9',
    description: 'Description for Reward 9',
    amount: 0.03,
    date: '2023-11-01',
  },
  {
    id: 9,
    creditCardId: 10,
    name: 'Reward 10',
    description: 'Description for Reward 10',
    amount: 0.04,
    date: '2023-11-02',
  },
  {
    id: 10,
    creditCardId: 1,
    name: 'Reward 11',
    description: 'Description for Reward 11',
    amount: 0.02,
    date: '2023-11-03',
  },
  {
    id: 11,
    creditCardId: 2,
    name: 'Reward 12',
    description: 'Description for Reward 12',
    amount: 0.03,
    date: '2023-11-04',
  },
  {
    id: 12,
    creditCardId: 3,
    name: 'Reward 13',
    description: 'Description for Reward 13',
    amount: 0.01,
    date: '2023-11-05',
  },
  {
    id: 13,
    creditCardId: 4,
    name: 'Reward 14',
    description: 'Description for Reward 14',
    amount: 0.04,
    date: '2023-11-06',
  },
  {
    id: 14,
    creditCardId: 5,
    name: 'Reward 15',
    description: 'Description for Reward 15',
    amount: 0.02,
    date: '2023-11-07',
  },
  {
    id: 15,
    creditCardId: 6,
    name: 'Reward 16',
    description: 'Description for Reward 16',
    amount: 0.03,
    date: '2023-11-08',
  },
  {
    id: 16,
    creditCardId: 7,
    name: 'Reward 17',
    description: 'Description for Reward 17',
    amount: 0.02,
    date: '2023-11-09',
  },
  {
    id: 17,
    creditCardId: 8,
    name: 'Reward 18',
    description: 'Description for Reward 18',
    amount: 0.01,
    date: '2023-11-10',
  },
  {
    id: 18,
    creditCardId: 9,
    name: 'Reward 19',
    description: 'Description for Reward 19',
    amount: 0.03,
    date: '2023-11-11',
  },
  {
    id: 19,
    creditCardId: 10,
    name: 'Reward 20',
    description: 'Description for Reward 20',
    amount: 0.04,
    date: '2023-11-12',
  },
];

const Consts: ConstsType = {
  authErrorMessages: AuthErrorMessages,
  dummyProfile: dummyProfile,
  dummyCreditCards: dummyCreditCards,
  dummyCreditCardRewards: dummyCreditCardRewards,
};

export default Consts;
